# 🚀 Project 1: Personal Expense Tracker

## 📌 Project Overview

A beginner-friendly Python project to build a **Personal Expense Tracker**.

The program will allow users to record their daily expenses and analyze their spending.

---

## 🎯 Project Goal

Build a Python program that can:

- Add a new expense
- Store the date of the expense
- Store the expense category
- Store the amount
- View all expenses
- Calculate total spending
- Find the highest expense
- Find spending by category
- Save expenses to a CSV file

---

## 🛠️ Technologies

For this project, use **Python only**.

```text
Python
├── Variables
├── Data Types
├── if / else
├── Loops
├── Functions
├── Lists
├── Dictionaries
├── File Handling
└── CSV

In [91]:
from datetime import date,datetime
expenses={}
def expense_on_item():
  item=input("Enter item name like grocery,books,other: ").lower().strip()
  amount=float(input('enter amount: '))
  a=input("Enter 'today' or enter date in format dd/mm/yyyy: ").lower()
  if a=='today':
    date_=date.today()
  else:
    date_ = datetime.strptime(a, "%d/%m/%Y").date()
  if not expenses.get(date_):
    expenses[date_]={}
    data=expenses[date_]
    data[str(item)]=data.get(str(item),0)+amount
    return
  data=expenses[date_]
  data[str(item)]=data.get(str(item),0)+amount

In [92]:
expense_on_item()
expenses

Enter item name like grocery,books,other: grocery
enter amount: 100
Enter 'today' or enter date in format dd/mm/yyyy: today

{datetime.date(2026, 10, 5): {'grocery': 100.0}}

In [93]:
expense_on_item()
expenses

Enter item name like grocery,books,other: books
enter amount: 2000
Enter 'today' or enter date in format dd/mm/yyyy: today

{datetime.date(2026, 10, 5): {'grocery': 100.0, 'books': 2000.0}}

In [94]:
expense_on_item()
expenses

Enter item name like grocery,books,other: others
enter amount: 10
Enter 'today' or enter date in format dd/mm/yyyy: today

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0}}

In [95]:
expense_on_item()
expenses

Enter item name like grocery,books,other: grocery
enter amount: 120
Enter 'today' or enter date in format dd/mm/yyyy: 04/10/2026

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0},
 datetime.date(2026, 10, 4): {'grocery': 120.0}}

In [97]:
expense_on_item()
expenses

Enter item name like grocery,books,other: books
enter amount: 1200
Enter 'today' or enter date in format dd/mm/yyyy: 04/10/2026

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0},
 datetime.date(2026, 10, 4): {'grocery': 120.0, 'books': 1200.0}}

In [98]:
expense_on_item()
expenses

Enter item name like grocery,books,other: others
enter amount: 50
Enter 'today' or enter date in format dd/mm/yyyy: 04/10/2026

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0},
 datetime.date(2026, 10, 4): {'grocery': 120.0,
  'books': 1200.0,
  'others': 50.0}}

In [99]:
expenses

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0},
 datetime.date(2026, 10, 4): {'grocery': 120.0,
  'books': 1200.0,
  'others': 50.0}}

In [100]:
def total_expenses_a_day():
  a=input("Enter 'today' or enter date in format dd/mm/yyyy: ").lower()
  if a=='today':
    date_=date.today()
  else:
    date_ = datetime.strptime(a, "%d/%m/%Y").date()
  if expenses.get(date_) :
    data=expenses[date_]
    total=0
    for _,i in data.items():
      total+=i
    return total
  return 0

In [101]:
total_expenses_a_day()

Enter 'today' or enter date in format dd/mm/yyyy: today

2110.0

In [102]:
total_expenses_a_day()

Enter 'today' or enter date in format dd/mm/yyyy: 04/10/2026

1370.0

In [103]:
def total_expenses():
  total=0
  for i in expenses:
    data=expenses[i]
    for _,i in data.items():
      total+=i
  return total

In [104]:
total_expenses()

3480.0

In [105]:
def spending_by_item():
  item=input("Enter item name like grocery,books,other")
  total=0
  for i in expenses:
    data=expenses[i]
    total+=data.get(item,0)
  print("total amount spend on this item :")
  return total

In [106]:
spending_by_item()

Enter item name like grocery,books,othergrocery
total amount spend on this item :

220.0

In [107]:
expenses

{datetime.date(2026, 10, 5): {'grocery': 100.0,
  'books': 2000.0,
  'others': 10.0},
 datetime.date(2026, 10, 4): {'grocery': 120.0,
  'books': 1200.0,
  'others': 50.0}}

In [108]:
def find_highest_expenses():
  highest_amount=0
  highest_day_total=0
  for i in expenses:
    total=0
    data=expenses[i]
    for it,j in data.items():
      total+=j
      if highest_amount<j:
        highest_amount=max(highest_amount,j)
        item=it
        date_=i
    if highest_day_total<total:
      s_date=i
      highest_day_total=max(highest_day_total,total)
  return f'Highest individual expense: {item} - ₹{highest_amount} on {date_.strftime("%d/%m/%Y")} \n Highest spending day: {s_date.strftime("%d/%m/%Y")} - ₹{highest_day_total}'

In [109]:
find_highest_expenses()

'Highest individual expense: books - ₹2000.0 on 05/10/2026 \n Highest spending day: 05/10/2026 - ₹2110.0'

In [110]:
import pandas as pd

In [111]:
data_all=[]
idx=[]
for i in expenses:
  idx.append(i)
  data=expenses[i]
  data_all.append(data)
data_all

[{'grocery': 100.0, 'books': 2000.0, 'others': 10.0},
 {'grocery': 120.0, 'books': 1200.0, 'others': 50.0}]

In [112]:
df = pd.DataFrame(data_all, index=idx)
df.index.name = "Date"
df

            grocery   books  others
Date
2026-10-05    100.0  2000.0    10.0
2026-10-04    120.0  1200.0    50.0

In [113]:
df.to_csv("expenses.csv")

In [114]:
pd.read_csv('expenses.csv')

         Date  grocery   books  others
0  2026-10-05    100.0  2000.0    10.0
1  2026-10-04    120.0  1200.0    50.0